#!/usr/bin/bash

#SBATCH --job-name=simple-solver-run
#SBATCH --output=output/%A_%4a.out
#SBATCH --error=output/%A_%4a.err
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --time=12:00:00
#SBATCH --partition=hslinux
#SBATCH --array=0-89

TRIAL_SIZE=1000
N_SIZES=(20 30 40 50 60 70 80 90 100)
N_PROGRAMS=10

N_INDEX=$(($SLURM_ARRAY_TASK_ID / $N_PROGRAMS))
N_SIZE=${N_SIZES[$N_INDEX]}

PROGRAM_ID=$(($SLURM_ARRAY_TASK_ID % $N_PROGRAMS))

java Main $TRIAL_SIZE $N_SIZE data/stateData_2000_${N_SIZE}_ID${PROGRAM_ID}.csv $PROGRAM_ID